id: PA5BDA4CE
initial_creation_type: input
source_metadata:
  Title: Dhīh Journal
  Editor: Prof. Geshe Ngawang Samten
  Publisher: Central University of Tibetan Studies
  Place of Publication: Sarnath, Varanasi
  Year: '2013'
  Śrīcakrasambarābhisamayavyākhyā:
    Text Version: Romanized
    Input Personnel: Rashmi Shakya
    Input Date: '2017'
    Proof Reader: Rashmi Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:03:32.463501'
last_modified_at: '2022-03-08T17:03:32.463510'
